# Generated by Django 4.1.4 on 2023-01-24 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makeproduct',
            old_name='loss',
            new_name='makeproduct_price',
        ),
        migrations.RenameField(
            model_name='makeproduct',
            old_name='price_makeproduct',
            new_name='pro_loss_makeproduct',
        ),
        migrations.RenameField(
            model_name='makeproduct',
            old_name='profit',
            new_name='pro_loss_purchaseproduct',
        ),
        migrations.AddField(
            model_name='makeproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='makeproduct',
            name='status_makeproduct',
            field=models.CharField(blank=True, choices=[('profit', 'profit'), ('loss', 'loss')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='makeproduct',
            name='status_purchaseproduct',
            field=models.CharField(blank=True, choices=[('profit', 'profit'), ('loss', 'loss')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Purchase_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_pro_fromshop', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(blank=True, choices=[('profit', 'profit'), ('loss', 'loss')], max_length=100, null=True)),
                ('org_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.makeproduct')),
            ],
        ),
    ]
