# Generated by Django 4.1.4 on 2023-01-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_loss_makeproduct_makeproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeproduct',
            name='product_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
