# Generated by Django 4.1.4 on 2023-01-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_makeproduct_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
            preserve_default=False,
        ),
    ]
