# Generated by Django 4.1.4 on 2023-01-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_makeproduct_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeproduct',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
