# Generated by Django 4.1.4 on 2023-01-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_makeproduct_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
