# Generated by Django 4.1.4 on 2023-01-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_makeproduct_sell_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeproduct',
            name='makeproduct_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='makeproduct',
            name='pro_loss_makeproduct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
