# Generated by Django 4.1.4 on 2023-01-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_makeproduct_makeproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
