# Generated by Django 4.1.4 on 2023-01-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_makeproduct_price_pro_fromshop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
    ]
